services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - crm_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - crm_network

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    networks:
      - crm_network

  celery:
    build:
      context: ./crm_project_vacancy
    command: celery -A crm_project_vacancy worker --loglevel=info
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project_vacancy.settings
      - PYTHONPATH=/app
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    networks:
      - crm_network

  django:
    build:
      context: ./crm_project_vacancy
    command: bash -c "sleep 30 && python /app/manage.py migrate && python /app/manage.py test && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - postgres
      - redis
      - celery
    networks:
      - crm_network

volumes:
  postgres_data:

networks:
  crm_network:
